FROM node:24.10.0-alpine

WORKDIR /app

COPY package.json */package-lock.json* ./

# Instalar dependências baseado no lockfile presente
RUN npm install --only=production

# Copiar o restante dos arquivos do projeto
COPY . .

RUN npm run build

EXPOSE 3000

CMD ["node", "dist/server.js"]