export enum BotState {
  INICIO = "INICIO",
  COLETANDO_SERVICO = "COLETANDO_SERVICO",
  SELECIONANDO_PROFISSIONAL = "SELECIONANDO_PROFISSIONAL",
  COLETANDO_DATA = "COLETANDO_DATA",
  COLETANDO_HORARIO = "COLETANDO_HORARIO",
  VERIFICANDO_DISPONIBILIDADE = "VERIFICANDO_DISPONIBILIDADE",
  CONFIRMACAO = "CONFIRMACAO",
  AGUARDANDO_CONFIRMACAO = "AGUARDANDO_CONFIRMACAO",
  AGUARDANDO_ID_AGENDAMENTO = "AGUARDANDO_ID_AGENDAMENTO",
  FINALIZADO = "FINALIZADO"
}
